apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2023-11-16T17:07:37Z"
  generation: 102
  name: drupal
  namespace: argocd
  resourceVersion: "957616"
  uid: f7b7e058-53dd-44db-a16b-a527f0862b8f
spec:
  destination:
    namespace: drupal
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: drupal
    helm:
      parameters:
      - name: drupalEmail
        value: antonstal@yandex.ru
      - name: drupalPassword
        value: qweqweqwe
      - name: externalDatabase.database
        value: bn_drupal
      - name: externalDatabase.host
        value: 192.168.202.4
      - name: ingress.enabled
        value: "true"
      - name: externalDatabase.password
        value: bn_drupal
      - name: ingress.hostname
        value: drupal.k8s-2.sa
      - name: mariadb.enabled
        value: "false"
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.1.3
